addresses = {
  "Province 1": {
    "Taplejung": [
      "Sidingba Rural Municipality",
      "Sirijanga Rural Municipality",
      "Yangwarak Rural Municipality",
      "Phungling Municipality",
      "Aatharai Tribeni Rural Municipality",
      "Maiwakhola Rural Municipality",
      "Meringden Rural Municipality",
      "Mikwakhola Rural Municipality",
      "Phaktanlung Rural Municipality"
    ],
    "Sankhuwasabha": [
      "Dharmadevi Municipality",
      "Chainapur Municipality",
      "Panchakhapan Municipality",
      "Khandabari Municipality",
      "Sabhapokhari Rural Municipality",
      "Chichila Rural Municipality",
      "Silichong Rural Municipality",
      "Makalu Rural Municipality",
      "Bhotkhola Rural Municipality"
    ],
    "Solukhumbu": [
      "Likhu Pike Rural Municipality",
      "Solu Dhudhakunda Municipality",
      "Necha Salyan Rural Municipality",
      "Dhudha Koushika Rural Municipality",
      "Dhudhakoshi Rural Municipality",
      "Sotang Rural Municipality",
      "Mahakulung Rural Municipality",
      "Khumbu Pasanglhamu Rural Municipality"
    ],
    "Okhaldhunga": [
      "Manebhanjyang Rural Municipality",
      "Champadevi Rural Municipality",
      "Khiji Demba Rural Municipality",
      "Molung Rural Municipality",
      "Siddhicharan Municipality",
      "Chishankhu Gadhi Rural Municipality"
    ],
    "Khotang": [
      "Baraha Pokhari Rural Municipality",
      "Jante Dhunga Rural Municipality",
      "Khotehang Rural Municipality",
      "Diprung Rural Municipality",
      "Sakela Rural Municipality",
      "Rupakot Majhuwagadhi Municipality",
      "Halesi Tuwachung Municipality",
      "Lamidanda Rural Municipality",
      "Aiselukharka Rural Municipality",
      "Kepilasgadhi Rural Municipality"
    ],
    "Bhojpur": [
      "Aamchowk Rural Municipality",
      "Hatuwagadhi Rural Municipality",
      "Ramprasad Rai Rural Municipality",
      "Pauwa Dunma Rural Municipality",
      "Arun Rural Municipality",
      "Bhojpur Municipality",
      "Tyamke Maiyum Rural Municipality",
      "Salpa Silichho Rural Municipality",
      "Shadananda Municipality"
    ],
    "Dhankuta": [
      "Chaubise Rural Municipality",
      "Sangurigadhi Rural Municipality",
      "Khalsa Chhintang Sahidbhumi Rural Municipality",
      "Dhankuta Municipality",
      "Chhathar Jorpati Rural Municipality",
      "Pakhribas Municipality",
    ],
    "Terhathum": [
      "Chhathar Rural Municipality",
      "Laligurans Municipality",
      "Myanglung Municipality",
      "Menchhayayem Rural Municipality",
      "Phedap Rural Municipality",
      "Aatharai Rural Municipality"
    ],
    "Panchthar": [
      "Tumbewa Rural Municipality",
      "Kummayak Rural Municipality",
      "Falgunanda Rural Municipality",
      "Phidim Municipality",
      "Falelung Rural Municipality",
      "Hilihan Rural Municipality",
      "Yangbarak Rural Municipality"
    ],
    "Ilam": [
      "Rong Rural Municipality",
      "Suryodaya Municipality",
      "Mai Municipality",
      "Chulachuli Rural Municipality",
      "Mangsebung Rural Municipality",
      "Fakfokathum Rural Municipality",
      "Deumai Municipality",
      "Ilam Municipality",
      "Sandakpur Rural Municipality",
      "Mai Jogmai Rural Municipality"
    ],
    "Jhapa": [
      "Kachanakawal Rural Municipality",
      "Bhadrapur Municipality",
      "Haldibari Rural Municipality",
      "Birtamod Municipality",
      "Barhadashi Rural Municipality",
      "Jhapa Rural Municipality",
      "Gauriganj Rural Municipality",
      "Gauradaha Municipality",
      "Damak Municipality",
      "Kamal Rural Municipality",
      "Shivasatakshi Municipality",
      "Kankai Municipality",
      "Arjundhara Municipality",
      "Buddhashanti Rural Municipality",
      "Mechinagar Municipality"
    ],
    "Morang": [
      "Jahada Rural Municipality",
      "Dhanapalthan Rural Municipality",
      "Katahari Rural Municipality",
      "Biratnagar Metropolitian City",
      "Budhiganga Rural Municipality",
      "Gramthan Rural Municipality",
      "Rangeli Municipality",
      "Sunwarshi Municipality",
      "Ratuwamai Municipality",
      "Urlabari Municipality",
      "Pathari Shanishchare Municipality",
      "Kanepokhari Rural Municipality",
      "Belbari Municipality",
      "Sundarharaicha Municipality",
      "Kerabari Rural Municipality",
      "Letang Municipality",
      "Miklajung Rural Municipality"
    ],
    "Sunsari": [
      "Barju Rural Municipality",
      "Dewangunj Rural Municipality",
      "Harinagara Rural Municipality",
      "Inaruwa Municipality",
      "Gadhi Rural Municipality",
      "Duhabi Municipality",
      "Itahari Sub-Metropolitian City",
      "Ramdhuni Municipality",
      "Bhokraha Rural Municipality",
      "Koshi Rural Municipality",
      "Baraha Municipality",
      "Dharan Sub-Metropolitian City"
    ],
    "Udayapur": [
      "Udayapurgadhi Rural Municipality",
      "Katari Municipality",
      "Tapli Rural Municipality",
      "Rautamai Rural Municipality",
      "Triyuga Municipality",
      "Chaudandigadhi Municipality",
      "Belaka Municipality"
    ]
  },
  "Province 2": {
    "Saptari": [
      "Chhinnamasta Rural Municipality",
      "Tilathi Koiladi Rural Municipality",
      "Hanumannagar Kankalini Municipality",
      "Tirahut Rural Municipality",
      "Mahadewa Rural Municipality",
      "Rajbiraj Municipality",
      "Bishnupur Rural Municipality",
      "Belhi Chapena Rural Municipality",
      "Dakneshwori Municipality",
      "BodeBarsain Municipality",
      "Balan-Bihul Rural Municipality",
      "Surunga Municipality",
      "Khadak Municipality",
      "Shambhunath Municipality",
      "Rupani Rural Municipality",
      "Agnisair Krishna Sabaran Rural Municipality",
      "Kanchanrup Municipality",
      "Saptakoshi Municipality"
    ],
    "Siraha": [
      "Siraha Municipality",
      "Aurahi Rural Municipality",
      "Bariyarpatti Rural Municipality",
      "Nawarajpur Rural Municipality",
      "Bhagawanpur Rural Municipality",
      "Sakhuwa Nankarkatti Rural Municipality",
      "Laxmipur Patari Rural Municipality",
      "Sukhipur Municipality",
      "Arnama Rural Municipality",
      "Naraha Rural Municipality",
      "Kalyanpur Municipality",
      "Karjanha Municipality",
      "Mirchaiya Municipality",
      "Golbazar Municipality",
      "Dhangadhimai Municipality",
      "Lahan Municipality"
    ],
    "Dhanusa": [
      "Mukhiyapatti Musaharmiya Rural Municipality",
      "Nagarain Municipality",
      "Dhanauji Rural Municipality",
      "Janakpur Sub-Metropolitian City",
      "Bideha Municipality",
      "Janak Nandini Rural Municipality",
      "Kamala Municipality",
      "Shahidnagar Municipality",
      "Sabaila Municipality",
      "Hansapur Municipality",
      "Mithila Bihari Municipality",
      "Laxminiya Rural Municipality",
      "Chhireshwornath Municipality",
      "Bateshwor Rural Municipality",
      "Mithila Municipality",
      "Dhanushadham Municipality",
      "Ganeshman Charnath Municipality"
    ],
    "Mahottari": [
      "Jaleshwor Municipality",
      "Matihani Municipality",
      "Pipara Rural Municipality",
      "Mahottari Rural Municipality",
      "Ekadara Rural Municipality",
      "Manara Shisawa Municipality",
      "Samsi Rural Municipality",
      "Ram Gopalpur Municipality",
      "Balawa Municipality",
      "Loharpatti Municipality",
      "Bhangaha Municipality",
      "Aurahi Municipality",
      "Sonama Rural Municipality",
      "Gaushala Municipality",
      "Bardibas Municipality"
    ],
    "Sarlahi": [
      "Malangawa Municipality",
      "Kaudena Rural Municipality",
      "Bishnu Rural Municipality",
      "Godaita Municipality",
      "Balara Municipality",
      "Ramnagar Rural Municipality",
      "Dhanakaul Rural Municipality",
      "Basbariya Rural Municipality",
      "Chakraghatta Rural Municipality",
      "Kabilashi Municipality",
      "Chandranagar Rural Municipality",
      "Brahmapuri Rural Municipality",
      "Parsa Rural Municipality",
      "Haripurwa Municipality",
      "Ishworpur Municipality",
      "Haripur Municipality",
      "Barahathawa Municipality",
      "Bagmati Municipality",
      "Hariwan Municipality",
      "Lalbandi Municipality"
    ],
    "Rautahat": [
      "Ishanath Municipality",
      "Gaur Municipality",
      "Rajdevi Municipality",
      "Durga Bhagawati Rural Municipality",
      "Yamunamai Rural Municipality",
      "Rajpur Municipality",
      "Paroha Municipality",
      "Boudhimai Municipality",
      "Maulapur Municipality",
      "Dewahi Gonahi Municipality",
      "Garuda Municipality",
      "Madhav Narayan Municipality",
      "Gadhimai Municipality",
      "Brindaban Municipality",
      "Katahariya Municipality",
      "Phatuwa Bijayapur Municipality",
      "Gujara Municipality",
      "Chandrapur Municipality"
    ],
    "Bara": [
      "Subarna Rural Municipality",
      "Devtal Rural Municipality",
      "Mahagadhimai Municipality",
      "Pacharauta Municipality",
      "Simroungadh Municipality",
      "Aadarsha Kotwal Rural Municipality",
      "Baragadhi Rural Municipality",
      "Karaiyamai Rural Municipality",
      "Kalaiya Sub-Metropolitian City",
      "Pheta Rural Municipality",
      "Bishrampur Rural Municipality",
      "Prasauni Rural Municipality",
      "Parawanipur Rural Municipality",
      "Jitpur Simara Sub-Metropolitian City",
      "Kolhabi Municipality",
      "Nijagadh Municipality"
    ],
    "Parsa": [
      "Bindabasini Rural Municipality",
      "Pakaha Mainpur Rural Municipality",
      "Chhipaharmai Rural Municipality",
      "Dhobini Rural Municipality",
      "Kalikamai Rural Municipality",
      "Pokhariya Municipality",
      "Bahudarmai Municipality",
      "Birgunj Metropolitian City",
      "Parsagadhi Municipality",
      "Sakhuwa Prasauni Rural Municipality",
      "Paterwa Sugauli Rural Municipality",
      "Jagarnathpur Rural Municipality",
      "Jirabhawani Rural Municipality",
      "Thori Rural Municipality"
    ]
  },
  "Province 3": {
    "Dolakha": [
      "Bhimeshwor Municipality",
      "Shailung Rural Municipality",
      "Melung Rural Municipality",
      "Tamakoshi Rural Municipality",
      "Jiri Municipality",
      "Baitedhar Rural Municipality",
      "Kalinchowk Rural Municipality",
      "Bigu Rural Municipality",
      "Gaurishankar Rural Municipality"
    ],
    "Sindhupalchok": [
      "Lisankhu Pakhar Rural Municipality",
      "Bahrabise Municipality",
      "Balephi Rural Municipality",
      "Choutara Sangachowkgadhi Municipality",
      "Indrawoti Rural Municipality",
      "Melanchi Municipality",
      "Helambu Rural Municipality",
      "Panchpokhari Thangpal Rural Municipality",
      "Jugal Rural Municipality",
      "Bhotekoshi Rural Municipality"
    ],
    "Rasuwa": [
      "Naukunda Rural Municipality",
      "Kalika Rural Municipality",
      "Uttargaya Rural Municipality",
      "Parbatikunda Rural Municipality",
      "Gosaikunda Rural Municipality"
    ],
    "Dhading": [
      "Dhunibenshi Municipality",
      "Thakre Rural Municipality",
      "Galchhi Rural Municipality",
      "Gajuri Rural Municipality",
      "Benighat Rorang Rural Municipality",
      "Siddhalek Rural Municipality",
      "Jwalamukhi Rural Municipality",
      "Nilkhantha Municipality",
      "Netrawati Rural Municipality",
      "Tripurasundari Rural Municipality",
      "Ganga Jamuna Rural Municipality",
      "Khaniyabas Rural Municipality",
      "Rubi Valley Rural Municipality"
    ],
    "Nuwakot": [
      "Kakani Rural Municipality",
      "Shivapuri Rural Municipality",
      "Panchakanya Rural Municipality",
      "Likhu Rural Municipality",
      "Belkotgadhi Municipality",
      "Tarakeshwor Rural Municipality",
      "Meghang Rural Municipality",
      "Kispang Rural Municipality",
      "Bidur Municipality",
      "Suryagadhi Rural Municipality",
      "Tadi Rural Municipality",
      "Dupcheshwor Rural Municipality"
    ],
    "Kathmandu": [
      "Dakshinkali Municipality",
      "Chandragiri Municipality",
      "Kirtipur Municipality",
      "Kathmandu Metropolitian City",
      "Nagarjun Municipality",
      "Tarakeshwor Municipality",
      "Tokha Municipality",
      "Budhanilkhantha Municipality",
      "Gokarneshwor Municipality",
      "Kageshwori Manahara Municipality",
      "Shankharapur Municipality"
    ],
    "Bhaktapur": [
      "Suryabinayak Municipality",
      "Madhyapur Thimi Municipality",
      "Bhaktapur Municipality",
      "Changunarayan Municipality"
    ],
    "Lalitpur": [
      "Bagmati Rural Municipality",
      "Mahankal Rural Municipality",
      "Konjyosom Rural Municipality",
      "Godawari Municipality",
      "Lalitpur Metropolitian City",
      "Mahalaxmi Municipality"
    ],
    "Kavrepalanchok": [
      "Khanikhola Rural Municipality",
      "Mahabharat Rural Municipality",
      "Roshi Rural Municipality",
      "Bethanchowk Rural Municipality",
      "Panauti Municipality",
      "Namobuddha Municipality",
      "Temal Rural Municipality",
      "Panchkhal Municipality",
      "Dhulikhel Municipality",
      "Banepa Municipality",
      "Mandan Deupur Municipality",
      "Bhumlu Rural Municipality",
      "Chauri Deurali Rural Municipality"
    ],
    "Ramechhap": [
      "Sunapati Rural Municipality",
      "Doramba Rural Municipality",
      "Khandadevi Rural Municipality",
      "Manthali  Municipality",
      "Ramechhap Municipality",
      "Gokulganga Rural Municipality",
      "Umakunda Rural Municipality"
    ],
    "Sindhuli": [
      "Hariharpurgaghi Rural Municipality",
      "Marin Rural Municipality",
      "Ghyanglekha Rural Municipality",
      "Sunkoshi Rural Municipality",
      "Kamalamai Municipality",
      "Golanjor Rural Municipality",
      "Tinpatan Rural Municipality",
      "Phikkal Rural Municipality",
      "Dudhouli Municipality"
    ],
    "Makwanpur": [
      "Bakaiya Rural Municipality",
      "Makawanpurgadhi Rural Municipality",
      "Bhimphedi Rural Municipality",
      "Hetauda Sub-Metropolitian City",
      "Manahari Rural Municipality",
      "Raksirang Rural Municipality",
      "Kailash Rural Municipality",
      "Thaha Municipality",
      "Indrasarowar Rural Municipality"
    ],
    "Chitawan": [
      "Madi Municipality",
      "Khairahani Municipality",
      "Ratnanagar Municipality",
      "Bharatpur Metropolitian City",
      "Ichchha Kamana Rural Municipality",
      "Kalika Municipality",
      "Rapti Municipality"
    ]
  },
  "Province 4": {
    "Gorkha": [
      "Gandaki Rural Municipality",
      "Shahid Lakhan Rural Municipality",
      "Gorkha Municipality",
      "Palungtar Municipality",
      "Siranchowk Rural Municipality",
      "Bhimsen Rural Municipality",
      "Aarughat Rural Municipality",
      "Dharche Rural Municipality",
      "Sulikot Rural Municipality",
      "Ajirkot Rural Municipality",
      "Chumanubri Rural Municipality"
    ],
    "Manang": [
      "Nashong Rural Municipality",
      "Chame Rural Municipality",
      "Neshang Rural Municipality",
      "Naraphu Rural Municipality"
    ],
    "Mustang": [
      "Thasang Rural Municipality",
      "Lomanthang Rural Municipality",
      "Bahragaun Muktikshetra Rural Municipality",
      "Gharpajhong Rural Municipality",
      "Dalome Rural Municipality"
    ],
    "Myagdi": [
      "Beni Municipality",
      "Mangala Rural Municipality",
      "Malika Rural Municipality",
      "Dhawalagiri Rural Municipality",
      "Raghuganga Rural Municipality",
    ],
    "Kaski": [
      "Rupa Rural Municipality",
      "Pokhara Lekhnath Metropolitian City",
      "Annapurna Rural Municipality",
      "Machhapuchchhre Rural Municipality",
      "Madi Rural Municipality"
    ],
    "Lamjung": [
      "Dudhapokhari Rural Municipality",
      "Rainas Municipality",
      "Sundarbazar Municipality",
      "Bensi Shahar Municipality",
      "Madhya Nepal Municipality",
      "Kwhola Sothar Rural Municipality",
      "Marshyangdi Rural Municipality",
      "Dordi Rural Municipality"
    ],
    "Tanahu": [
      "Aanbu Khaireni Rural Municipality",
      "Bandipur Rural Municipality",
      "Devghat Rural Municipality",
      "Rhishing Rural Municipality",
      "Ghiring Rural Municipality",
      "Bhimad Municipality",
      "Shuklagandaki Municipality",
      "Myagde Rural Municipality",
      "Byas Municipality",
      "Bhanu Municipality"
    ],
    "Nawalparasi East": [
      "Binayi Tribeni Rural Municipality",
      "Madhya Bindu Municipality",
      "Kawasoti Municipality",
      "Devchuli Municipality",
      "Hupsekot Rural Municipality",
      "Bungdikali Rural Municipality",
      "Bulingtar Rural Municipality",
      "Gaidakot Municipality"
    ],
    "Syangja": [
      "Kaligandaki Rural Municipality",
      "Galyang Municipality",
      "Walling Municipality",
      "Chapakot Municipality",
      "Harinas Rural Municipality",
      "Biruwa Rural Municipality",
      "Bhirkot Municipaity",
      "Arjun Choupari Rural Municipality",
      "Aandhikhola Rural Municipality",
      "Phedikhola Rural Municipality",
      "Putalibazar Municipality"
    ],
    "Parbat": [
      "Paiyu Rural Municipality",
      "Bihadi Rural Municipality",
      "Mahashila Rural Municipality",
      "Phalebas Municipality",
      "Kushma Municipality",
      "Jaljala Rural Municipality",
      "Modi Rural Municipality"
    ],
    "Baglung": [
      "Jaimuni Municipality",
      "Bareng Rural Municipality",
      "Galkot Municipality",
      "Badigad Rural Municipality",
      "Nisikhola Rural Municipality",
      "Dhorpatan Municipality",
      "Tamankhola Rural Municipality",
      "Tarakhola Rural Municipality",
      "Kathekhola Rural Municipality",
      "Baglung Municipality"
    ]
  },
  "Province 5": {
    "Rukum East ": [
      "Bhoome Rural Municipality",
      "Sisne Rural Municipality",
      "Putha Uttanganga Rural Municipality"
    ],
    "Rolpa": [
      "Lungri Rural Municipality",
      "Subarnabati Rural Municipality",
      "Runtigadhi Rural Municipality",
      "Rolpa Municipality",
      "Sukidaha Rural Municipality",
      "Duikholi Rural Municipality",
      "Thawang Rural Municipality",
      "Sunchhahari Rural Municipality"
    ],
    "Pyuthan": [
      "Sarumarani Rural Municipality",
      "Aairawati Rural Municipality",
      "Mallarani Rural Municipality",
      "Mandavi Rural Municipality",
      "Sworgadwari Municipality",
      "Pyuthan Municipality",
      "Jhimaruk Rural Municipality",
      "Naubahini Rural Municipality",
      "Gaumukhi Rural Municipality"
    ],
    "Gulmi": [
      "Ruru Rural Municipality",
      "Chhatrakot Rural Municipality",
      "Gulmi Durbar Gaunpaika",
      "Resunga Municipality",
      "Dhurkot Rural Municipality",
      "Madane Rural Municipality",
      "Isma Rural Municipality",
      "Chandrakot Rural Municipality",
      "Satyawoti Rural Municipality",
      "Kali Gandaki Rural Municipality"
    ],
    "Arghakhanchi": [
      "Shitaganga Municipality",
      "Panini Rural Municipality",
      "Sandhikharka Municipality",
      "Bhumikasthan Municipality",
      "Malarani Rural Municipality",
      "Chhatradev Rural Municipality"
    ],
    "Palpa": [
      "Nisdi Rural Municipality",
      "Mathagadhi Rural Municipality",
      "Tinau Rural Municipality",
      "Rainadevi Chhahara Rural Municipality",
      "Ribdikot Rural Municipality",
      "Tansen Municipality",
      "Baganaskali Rural Municipality",
      "Rambha Rural Municipality",
      "Purbakhola Rural Municipality",
      "Rampur Municipality"
    ],
    "Nawalparasi West": [
      "Susta Rural Municipality",
      "Pratapapur Rural Municipality",
      "Sarawal Rural Municipality",
      "Palhinandan Rural Municipality",
      "Ramgram Municipality",
      "Sunawal Municipality",
      "Bardaghat Municipality"
    ],
    "Rupandehi": [
      "Marchawari Rural Municipality",
      "Sammarimai Rural Municipality",
      "Kotahimai Rural Municipality",
      "Lumbini Sanskritik Municipality",
      "Mayadevi Rural Municipality",
      "Siddharthanagar Municipality",
      "Rohini Rural Municipality",
      "Om Satiya Rural Municipality",
      "Tilottama Municipality",
      "Siyari Rural Municipality",
      "Suddhodhan Rural Municipality",
      "Gaidahawa Rural Municipality",
      "Kanchan Rural Municipality",
      "Sainamaina Municipality",
      "Butwal Sub-Metropolitian City",
      "Devdaha Municipality"
    ],
    "Kapilbastu": [
      "Shuddhodhan Rural Municipality",
      "Yasodhara Rural Municipality",
      "Kapilbastu Municipality",
      "Maharajganj Municipality",
      "Krishnanagar Municipality",
      "Bijayanagar Rural Municipality",
      "Shivaraj Municipality",
      "Buddhabhumi Municipality",
      "Banganga Municipality"
    ],
    "Dang": [
      "Rajpur Rural Municipality",
      "Gadhawa Rural Municipality",
      "Rapti Rural Municipality",
      "Lamahi Municipality",
      "Dangisharan Rural Municipality",
      "Babai Rural Municipality",
      "Shantinagar Rural Municipality",
      "Tulsipur Sub-Metropolitian City",
      "Ghorahi Sub-Metropolitian City",
      "Bangalachuli Rural Municipality"
    ],
    "Banke": [
      "Narainapur Rural Municipality",
      "Duduwa Rural Municipality",
      "Nepalganj Sub-Metropolitian City",
      "Khajura Rural Municipality",
      "Baijanath Rural Municipality",
      "Kohalpur Municipality",
      "Rapti Sonari Rural Municipality"
    ],
    "Bardiya": [
      "Badhaiyatal Rural Municipality",
      "Gulariya Municipality",
      "Madhuwan Municipality",
      "Rajapur Municipality",
      "Geruwa Rural Municipality",
      "Thakurbaba Municipality",
      "Barbardiya Municipality",
      "Bansgadhi Municipality"
    ]
  },
  "Province 6": {
    "Dolpa": [
      "Chharka Tangsong Rural Municipality",
      "Kaike Rural Municipality",
      "Thulibheri Municipality",
      "Tripurasundari Municipality",
      "Mudkechula Rural Municipality",
      "Jagadulla Rural Municipality",
      "Shey Phoksundo Rural Municipality",
      "Dolpo Buddha Rural Municipality"
    ],
    "Mugu": [
      "Khatyad Rural Municipality",
      "Soru Rural Municipality",
      "Chhayanath Rara Municipality",
      "Mugumakarmarog Rural Municipality"
    ],
    "Humla": [
      "Tanjakot Rural Municipality",
      "Adanchuli Rural Municipality",
      "Sarkegad Rural Municipality",
      "Namkha Rural Municipality",
      "Simkot Rural Municipality",
      "Kharpunath Rural Municipality",
      "Chankheli Rural Municipality"
    ],
    "Jumla": [
      "Hima Rural Municipality",
      "Tila Rural Municipality",
      "Tatopani Rural Municipality",
      "Guthichaur Rural Municipality",
      "Chandannath Municipality",
      "Sinja Rural Municipality",
      "Kanaka Sundari Gaun Palika",
      "Patarasi Rural Municipality"
    ],
    "Kalikot": [
      "Mahawai Rural Municipality",
      "Tilagupha Municipality",
      "Khandachakra Municipality",
      "Naraharinath Rural Municipality",
      "Sanni Tribeni Rural Municipality",
      "Raskot Municipality",
      "Pachal Jharana Rural Municipality",
      "Palata Rural Municipality"
    ],
    "Dailekh": [
      "Gurans Rural Municipality",
      "Dungeshwor Rural Municipality",
      "Bhagawatimai Rural Municipality",
      "Narayan Municipality",
      "Dullu Municipality",
      "Chamunda Bindrasaini Municipality",
      "Aathbis Municipality",
      "Thantikandh Rural Municipality",
      "Bhairabi Rural Municipality",
      "Mahabu Rural Municipality",
      "Naumule Rural Municipality"
    ],
    "Jajarkot": [
      "Tribeni Nalagad Municipality",
      "Bheri Malika Municipality",
      "Shivalaya Rural Municipality",
      "Chhedagad Municipality",
      "Junichande Rural Municipality",
      "Kuse Rural Municipality",
      "Barekot Rural Municipality"
    ],
    "Rukum West ": [
      "Chaurjahari Municipality",
      "Musikot Municipality",
      "Banphikot Rural Municipality",
      "Sanibheri Rural Municipality",
      "Aathabisakot Municipality"
    ],
    "Salyan": [
      "Kapurkot Rural Municipality",
      "Tribeni Rural Municipality",
      "Kalimati Rural Municipality",
      "Sharada Municipality",
      "Chhatreshwori Rural Municipality",
      "Bagachour Municipality",
      "Dhorchaur Rural Municipality",
      "Banagad Kupinde Municipality",
      "Kumakh Malika Rural Municipality",
      "Darma Rural Municipality"
    ],
    "Surkhet": [
      "Chaukune Rural Municipality",
      "Panchapuri Municipality",
      "Barahatal Rural Municipality",
      "Birendranagar Municipality",
      "Bheriganga Municipality",
      "Gurbhakot Municipality",
      "Lekabeshi Municipality",
      "Chingad Rural Municipality",
      "Simta Rural Municipality"
    ]
  },
  "Province 7": {
    "Bajura": [
      "Tribeni Municipality",
      "Budhiganga Municipality",
      "Chhededaha Rural Municipality",
      "Badimalika Municipality",
      "Pandab Gufa Rural Municipality",
      "Swami Kartik Rural Municipality",
      "Budhinanda Municipality",
      "Gaumul Rural Municipality",
      "Himali Rural Municipality"
    ],
    "Bajhang": [
      "Khaptad Chhanna Rural Municipality",
      "Thalara Rural Municipality",
      "Bitthadchir Rural Municipality",
      "Kedarsyun Rural Municipality",
      "Durgathali Rural Municipality",
      "Chhabis Pathibhara Rural Municipality",
      "Jayaprithbi Municipality",
      "Masta Rural Municipality",
      "Talkot Rural Municipality",
      "Surma Rural Municipality",
      "Bungal Municipality",
      "Kanda Rural Municipality"
    ],
    "Darchula": [
      "Lekam Rural Municipality",
      "Malikarjun Rural Municipality",
      "Shailyashikhar Municipality",
      "Marma Rural Municipality",
      "Apihimal Rural Municipality",
      "Naugad  Rural Municipality",
      "Duhun Rural Municipality",
      "Byas Rural Municipality"
    ],
    "Baitadi": [
      "Sigas Rural Municipality",
      "Patam Municipality",
      "Melauli Municipality",
      "Shivanath Rural Municipality",
      "Pancheshwor Rural Municipality",
      "Dasharathchand Municipality",
      "Surnaya Rural Municipality",
      "Puchaundi Municipality",
      "Dogada Kedar Rural Municipality",
      "Dilasaini Rural Municipality"
    ],
    "Dadeldhura": [
      "Ganyapdhura Rural Municipality",
      "Aalital Rural Municipality",
      "Parashuram Municipality",
      "Bhageshwor Rural Municipality",
      "Ajayameru Rural Municipality",
      "Amargadhi Municipality",
      "Nawadurga Rural Municipality"
    ],
    "Doti": [
      "Jorayal Rural Municipality",
      "Badi Kedar Rural Municipality",
      "Bogatan Rural Municipality",
      "K.I. Singh Rural Municipality",
      "Dipayal Silgadhi Municipality",
      "Shikhar Municipality",
      "Aadarsha Rural Municipality",
      "Sayal Rural Municipality",
      "Purbichouki Rural Municipality"
    ],
    "Achham": [
      "Turmakhand Rural Municipality",
      "Dhakari Rural Municipality",
      "Kamal Bazar Municipality",
      "Bannigadhi Jayagadh Rural Municipality",
      "Mangalsen Municipality",
      "Chaurpati Rural Municipality",
      "Sanphebagar Municipality",
      "Mellekh Rural Municipality",
      "Ramaroshan Rural Municipality",
      "Panchdebal Binayak Municipality"
    ],
    "Kailali": [
      "Dhangadhi Sub-Metropolitian City",
      "Kailari Rural Municipality",
      "Bhajani Municipality",
      "Tikapur Municipality",
      "Joshipur Rural Municipality",
      "Janaki Rural Municipality",
      "Lamki Chuha Municipality",
      "Bardagoriya Rural Municipality",
      "Ghodaghodi Municipality",
      "Gauriganga Municipality",
      "Chure Rural Municipality",
      "Mohanyal Rural Municipality"
    ],
    "Kanchanpur": [
      "Beldandi Rural Municipality",
      "Belouri Municipality",
      "Punarbas Municipality",
      "Laljhadi Rural Municipality",
      "Mahakali Municipality",
      "Bhimdatta Municipality",
      "Bedkot Municipality",
      "Shuklaphanta Municipality",
      "Krishnapur Municipality"
    ]
  }
}
